function checkUpImg(fieldObj){var imgPath = fieldObj.value.replace(/(^\s*)|(\s*$)/g,"");if ( "" != imgPath ){
var imgExt = imgPath.substr(imgPath.lastIndexOf("."));imgExt = imgExt.toLowerCase();if ( imgExt != '.png' && imgExt != '.gif'){
alert("图片格式错误,请上传.png,.gif格式的图片！");return false;}return true;}else{ return true;}}function submitCheck() {
var result = true;result = promptMsg(textCheck('jmname',1,200), '部门名称不可为空','info1') && result;if ( result ) {
if(checkUpImg(document.getElementById("orgSignet"))){document.getElementById("addInfo").disabled = true;}else{result=false;}}return result;}
function clearInfo(spanId) {document.getElementById(spanId).innerHTML = "<font color=\"red\">*必填</font>";}
function selectOrg(){getDataDoC2("<%=basePath%>system/org!selectOrg.action?time="+new Date().getTime(),400,"ssjgcode","ssjgname","level");}
function selectPerson(){getDataDoC2("<%=basePath%>system/empl!selectMain.action?time="+new Date().getTime(),935,"emplId","emplName");var selectId = $("#emplId").val();
if (-1 != selectId.indexOf(",")) {alert("只可选择一个负责人");$("#emplId").val("");$("#emplName").val("");}}
function preImg(imgFile){if(!checkUpImg(document.getElementById("orgSignet"))){return;}$("#newPreview").empty();
var newPreview=document.getElementById("newPreview");if($.browser.version == 8.0||$.browser.version==6.0)
{var imgDiv=document.createElement("div");document.body.appendChild(imgDiv);imgDiv.style.width="118px";
imgDiv.style.height="127px";imgDiv.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=scale)";
imgDiv.filters.item("DXImageTransform.Microsoft.AlphaImageLoader").src=imgFile.value;
imgDiv.style.position="relative";newPreview.appendChild(imgDiv);}else{var img = document.createElement("img");img.setAttribute("src", "");img.setAttribute("id", "preview");newPreview.appendChild(img);$("#preview").attr("src",imgFile.value).show();}}
function goNextPage( currentPage ) {document.getElementById("reqPage").value = currentPage;document.forms.namedItem("queryForm").submit();	}function delCallBack() {document.forms.namedItem("queryForm").submit();}function getCheckBox(checkboxname, counts) {var selectCount = 0;var selectValue = "";var myselector = "input[type='checkbox'][name='"+checkboxname+"']";var checkboxs = $(myselector).each(function(){if($(this).attr("checked")==true){selectCount = selectCount + 1;selectValue = $(this).attr("value");}});if (1 == counts) {if (selectCount == counts) {return selectValue;}return "";} else if (-1 == counts) {if (selectCount >= 1) {return true;}return false;}return false;} 
function updateOrg(jmcode) {var selectVal = getCheckBox(jmcode,1);if ("" != selectVal) {self.parent.updateOrgInfo('${parentCode}',selectVal)} else {alert("有且只有一个复选框必须被选中");}}
function deleteOrg(jmcode){var selectResult = getCheckBox(jmcode,-1);if (selectResult) {if (confirm("您确定要删除所选的部门？")) {$("form[name='deleteForm']").submit();}} else {alert("至少有一个复选框必须被选中！");}}
function sureChose(tagName,btnId){var checkbox=document.getElementsByName(tagName);	var checkValue="";var checkTagName="";for(var i =0;i<checkbox.length;i++){if(checkbox[i].checked==true){checkValue+=checkbox[i].value+",";checkTagName+=checkbox[i].title+",";}}checkValue=checkValue.substring(0,checkValue.length-1);		checkTagName=checkTagName.substring(0,checkTagName.length-1);							if(checkValue.indexOf(",")==-1||checkTagName.indexOf(",")==-1){alert("您还没有选择合同类别。");return;}document.getElementById("returnName").value+=checkTagName+";";document.getElementById("returnValue").value+=checkValue+";";document.getElementById(btnId).disabled="disabled";}function orgCheck(tagName){var org = document.getElementById(tagName);if(org.checked==true){var checkbox=document.getElementsByName(tagName);										for(var i =0;i<checkbox.length;i++){checkbox[i].disabled=false;}}else{var checkbox=document.getElementsByName(tagName);										for(var i =0;i<checkbox.length;i++){checkbox[i].disabled="disabled";checkbox[i].checked=false;}}document.getElementById(tagName).disabled=false;}
function setValue(){var returnName=document.getElementById("returnName").value;var returnValue=document.getElementById("returnValue").value;if(returnName.length>1||returnName.indexOf(";")!=-1){returnName=returnName.substring(0,returnName.length-1);returnValue=returnValue.substring(0,returnValue.length-1);}var value=new Array(returnName,returnValue);		getDataC(returnName,returnValue);}
function showHtlb(org){var width=400;var height=400;var url="org!searchhtlb.action";var returnValue=window.showModalDialog(url,org, "dialogWidth=" + width + "px;dialogHeight=" + height + "px;resizable:yes;");				if(null!=returnValue&&undefined!=returnValue){var nowValue=document.getElementById("returnValue").value;if(nowValue!=""){nowValue+=";"+returnValue[0];}else{nowValue=returnValue[0];}document.getElementById("returnValue").value=nowValue;var nowName=document.getElementById("returnName").value;if(nowName!=""){nowName+=";"+returnValue[1];}else{nowName=returnValue[1];}document.getElementById("returnName").value=nowName;}}
function checkSame(nowValue,returnValue,id){var returnOrg=returnValue.substring(0,returnValue.indexOf(","));alert("截取的单位:"+returnOrg);				if(nowValue.indexOf(returnOrg)>-1){var subValue="";if(nowValue.indexOf(";")>0){subValue=nowValue.substring(nowValue.indexOf(returnOrg),(nowValue.indexOf(returnOrg)+nowValue.indexOf(";")+1));var subValues=nowValue.split(";");for(var i=0;i<subValues.length;i++){if(subValues[i].indexOf(returnOrg)>-1){subValue=subValues[i]}}if(nowValue.indexOf(";")!=nowValue.length){subValue+=";";}}else{subValue=nowValue.substring(nowValue.indexOf(returnOrg),nowValue.length);}alert("需要替换的值得："+subValue);nowValue=nowValue.replace(subValue,"");alert("最后"+nowValue);document.getElementById(id).value=nowValue;}return document.getElementById(id).value;}